# Generated by Django 4.0 on 2022-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exam_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_points',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
