# Generated by Django 4.0 on 2022-12-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_exam_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='level',
        ),
        migrations.RemoveField(
            model_name='point',
            name='exam',
        ),
        migrations.AddField(
            model_name='point',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_of_exam', to='app.level'),
        ),
    ]
