# Generated by Django 4.0 on 2022-12-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_exam_level_remove_point_exam_point_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
