# Generated by Django 4.0 on 2022-12-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
